# Abstract

Grounded-embodied theories hold that language is understood and remembered through perceptual and motor simulations (i.e., activations and re-activations of sensorimotor experiences). This thesis aims to illustrate simulations of space in memory for language. In four experiments, we explored (1) how individuals encode and re-activate word locations and (2) how word meanings activate locations in space (e.g., “bird” - upward location). In the first part of the thesis (Experiment 1 and 2), we addressed the potential simulation of word locations by probing eye movements during memory retrieval (i.e., “looking at nothing”). In particular, we investigated why and when individuals need to rely on external memory support via simulation of word locations. Experiment 1 results reveal that the propensity to refer to the environment during retrieval correlates with individual’s visuospatial memory capacity. That is, participants with worse visuospatial memory relied more on the environment; whereas, participants with better visuospatial memory relied more on the internal memory sources. Experiment 2 shows that words which are more difficult to remember and, particularly, words that are more difficult to visualise in mind lead to more reliance on the environment during word retrieval. Experiment 1 and 2 suggest that the opportunistic and efficient human mind switches between internal sources and external support as a function of the richness of internal sources and cognitive demands coming from the words to be remembered. The second part of the thesis (Experiment 3 and 4), focuses on spatial simulations triggered directly by words (i.e., language-based simulations). Experiment 3 is a norming study in which raters were asked to associate words with locations in space. Experiment 3 results demonstrate that there is a high degree of agreement among individuals when linking both concrete and abstract words to locations in space although there are no explicit conventions with regard to these associations. Ratings in Experiment 3 indicate potential locations of word-induced simulations. Normed words were used as stimuli in Experiment 4 in which recognition memory for words with spatial associations was probed. Experiment 4 results show that both language-based simulation of space and simulation of word locations dictate memory performance even if space is irrelevant and unnecessary for successful retrieval. In particular, words that were presented in incongruent locations as to the locations they imply (e.g., “bird” in a downward location) were remembered faster than words presented in congruent locations (e.g., “bird” in an upward location). Memory performance deteriorated whenever attention was shifted to the locations simulated with word meanings. Overall, the thesis specifies the mechanics of two different types of spatial simulation in language and their effects on memory. Results and their implications are discussed within the framework of grounded-embodied approaches to language and memory and the extended cognition.