title: Alper Kumcu
description: ex nihilo nihil fit

author:
  name: Alper Kumcu
  email: alperkumcu[at]gmail.com

show_excerpts: true

minima:
  skin: auto
  date_format: "%b %-d, %Y"
  nav_pages:
    - publications.md
    - talks.md
    - scicomm.md
    - activities.md
    - teaching.md
    - multimedia.md
  social_links:
    - title: X
      icon: x-twitter
      url: "https://x.com/alperkumcu"
    - title: YouTube
      icon: youtube
      url: "https://www.youtube.com/@alperkumcu"
    - title: LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/alperkumcu"
    - title: Instagram
      icon: instagram
      url: "https://www.instagram.com/alperkumcu"

# Google Analytics
google_analytics: UA-48656742-3

# Build settings
remote_theme: "jekyll/minima@1e8a445"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme