# Acknowledgement

What a roller-coaster of emotions! The thesis you are reading now was made possible through scientific, mental and emotional support of many people, which makes me a very lucky researcher. Here, I would like to name a few, and I apologise in advance to all others that I forgot to mention.

First and foremost, I would like to thank my supervisor Dr Robin L. Thompson for her never-ending support, meticulous supervision and invaluable insights. She shared my joy during success and she lifted me up during moments of anxiety (which I had a lot). Without her, I could not even imagine realising my dream of doing a PhD in psychology. Thank you for being a great person and a great supervisor.
Language and Psychology Lab Group had a huge impact on me as a researcher and the present thesis. I would like to thank Professor Linda Wheeldon for never leaving my questions unanswered, Dr Steven Frisson for his contributions to the present work with his questions and constructive feedback, Dr Katrien Segaert for her support in mixed-effects modelling and for being a role model with her research and lively presentations, Dr Andrew Olson, Dr Andrea Krott and also Professor Sotaro Kita from University of Warwick for their helpful suggestions on the experiments reported in this thesis.

My friends and colleagues here in UK deserve special thanks. Many thanks to Evi Argyriou for providing an inspiring example with her minimalist approach to research and presentation, Freya Atkins for being such a great (lab) mate, Mahmoud Elsherif for our fruitful debates about science and life in general, Isabella Fritz for our discussions in grounded-embodied cognition and R, Anneline Huck from University College London and Beinan Zhou for their support in collecting the pilot data, Linde Luijnenburg for her company at the British Library, Rachel Merchant for her support in recording the auditory stimuli, Kristian Suen for the teamwork in organising Language and Cognition Seminars (LanCoS) and Onur Usta for the library sessions and gallons of coffee.

I would like to acknowledge Turkish Council of Higher Education and Hacettepe University for awarding me with a doctoral scholarship and funding my research. I am grateful to my colleagues and friends at Hacettepe University in Turkey; especially Dr Sinem Sancaktaroğlu Bozkurt, Dr Hilal Erkazancı Durmuş, Dr Elif Ersözlü and Dr Sezen Ergin Zengin for smoothing out the funding process and for their lovely companionship.

I would like to thank all the participants who kindly participated the experiments. It goes without saying that the research could not be conducted without them. I also would like to thank our omniscient post-grad administrator Parveen Chahal for answering millions of questions that I have asked during my years at the School of Psychology.

Last but not least, I am deeply grateful to my mother and sister, who have sent their affection and support from miles away. The majority of the people I mentioned here is woman. A heartfelt appreciation to all women in science!